#! /usr/bin/env python

from fusionfusion.run import *
import argparse

parser = argparse.ArgumentParser(prog = "fusionfusion")

parser.add_argument("--version", action = "version", version = "fusionfusion-0.1.0")

parser.add_argument("--star", metavar = "star_chimera.sam", default = None, type = str,
                    help = "the path to the chimeric sam file by STAR")

parser.add_argument("--ms2", metavar = "ms2.bam", default = None, type = str,
                    help = "the path to the bam file by map-splice2")

parser.add_argument("--out", metavar = "output_dir", default = None, type = str, required=True,
                    help = "the path to the output directory")

parser.add_argument("--param", metavar = "param.cfg", type = str, required=True,
                    help = "parameter information file (to be parsed by ConfigParser module)")

args = parser.parse_args()

main(args)
