---
# path to blat binary
blat_path: /usr/local/bin/blat

# option used in blat
blat_option: -stepSize=5 -repMatch=2253

# debug_mode is boolean key (True or False). When True, many intermediate files are remained for debugging.
debug_mode: False

# the size of abnormal insert size. used for checking the consistency of paired read of breakpoint containing reads
abnormal_insert_size: 500000


# the threshold of supporting junction read pairs
min_read_pair_num: 3

# the minimum ratio of proper supporting junction read pairs (used for map-splice2)
min_valid_read_pair_ratio: 0.8

# the minimum region size which have to be covered by aligned short reads
min_cover_size: 50

# the threshold of minimum chimeric transcript sizes
min_chimeric_size: 1000
