---
# software is the parent key for software information
software
    # path to blat binary
    blat: /usr/local/bin/blat

    # option used in blat
    blat_option: -stepSize=5 -repMatch=2253

# debug_mode is boolean key (True or False). When True, many intermediate files are remained for debugging.
debug_mode: False

# the size of abnormal insert size. used for checking the consistency of paired read of breakpoint containing reads
abnormal_insert_size: 500000
